security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory:
                memory:
                    users:
                        glavergne001: { password: $2y$10$P0NmmHmpVzWpvkvn5tXcWu/GWlnMStWRPbyXMIi48Z/pBF3rozBuW, roles: [ROLE_ADMIN,ROLE_USER] }
                        julaisse: { password: $2y$10$HpArWQUOKCwwr..fb/u9rOIArr9HEwUzDzxuH5G.gC6bd.G6.GAxy, roles: ROLE_USER }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: users_in_memory

            http_basic: true
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 10
